### ISSUE TITLE
Avoid Parallel junctions in rotationally symmetric tubes

### ISSUE THREAD

**Issue by DNAcer** [404Wolf/NATuG#8] opened 2022-11-25 03:58 UTC
I just noticed a problem I had not considered previously. If you create a rotationally symmetric tube with an odd number of DNA domains per subunit, and if the first subunit has all antiparallel junctions with 0 strand switches, then at the boundary between subunits you end up with parallel junctions. See attached picture, and note that the yellow strand changes directions as it goes from domain 1 to 2 to 3 from up to down to up. However, when it goes from 3 to 4, it goes from the up helix in 3 to the up helix in 4. That's the logical thing for it to do, but in practice, people will want all antiparallel junctions most of the time, so we should probably put in a check box that says "Always antiparallel junctions", and if the user checks yes (which should be the default), then the left junction of each domain added under symmetry operations should be the opposite of the right junction of the previous domain, and the right junction of each domain added under symmetry operations should be the opposite of the left junction of the previous domain. Ask me about it if that explanation is too confusing (or if you have a better strategy for dealing with this).
<img width="976" alt="Screen Shot 2022-11-24 at 10 33 51 PM" src="https://user-images.githubusercontent.com/118033291/203898490-ee39b7dd-a70d-4963-9f7d-29e3aae804c3.png">

**Comment by 404Wolf** [comment] 2022-11-27 02:40
@DNAcer 
I just implemented this. When you get a chance, if you could check over the implementation and close this issue if it's been updated as intended, that'd be great. Thanks!

![image](https://user-images.githubusercontent.com/108041238/204116714-5bb1aae5-aa8f-4c6c-848d-c303f1d24d44.png)
![image](https://user-images.githubusercontent.com/108041238/204116717-224dd13a-54d4-4117-9887-9ba20715ef11.png)

**Closed** 2022-11-30 20:40 UTC
Labels: feature request, medium priority
